### PR TITLE
Fix: Issue templates all saying "Modrinth Website"

### PR DESCRIPTION
**Pull request by blryface**
On the issues template, the App, Website and API templates all say "Report an issue on the Modrinth **website**"
image

### CODE REVIEW

**Comment by blryface** [comment]
screw @ktrain :(

**Comment by blryface** [comment]
image
OH NO

**Comment by KTrain5169** [comment]
bruh

**Comment by blryface** [comment]
Reopening because apparently the other one was closed (?)

**Comment by brawaru** [comment]
> image
> OH NO

You know what else is polarised other than the issue reporting options? The news we see every day. This is why today's pull request is sponsored by Ground News. Ground News is a website that allows you view the same news in different perspectives, from both and left and right leaning media. I personally love their Blindspot feature, which allows you to see news which very predominantly by only one of the sides. Check Ground News out and subscribe to see more stories—use the link in the description and get your first month for free. Thanks Ground News for sponsoring this pull request. Now, back onto the merge.

**Pull request closed without merging**
