### PR TITLE
Pyro Integration

### PR DESCRIPTION
**Pull request by ChecksumDev**
Had to move this to a branch inside upstream for use internally, development will now proceed here.

### CODE REVIEW

**Comment by MagmaBro123** [comment]
Sooo..... What is this for? Why is a control panel needed?

**Review by he3als — APPROVED** [review]
lgtm probably

**Comment by fangmarks** [comment]
lgtm 2

**Review by Prospector — APPROVED** [review]
lgtm

**Comment by thewander02** [comment]
lgtm

**Comment by not-nullptr** [comment]
i love you all lgtm

**Review by Geometrically — APPROVED** [review]

**Review by ferothefox — APPROVED** [review]
lgtm

**Comment by not-nullptr** [comment]
hi evan :)

**Comment by he3als** [comment]
waiting...

**Comment by izmystic** [comment]
🦑

**Comment by not-nullptr** [comment]
maddie was here!!!!!

**Pull request merged**
