### PR TITLE
fix: not being able to Follow/Save/Report projects

### LINKED ISSUE #2172: Project Follow/Save/Report buttons not working
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)

### What browsers are you seeing the problem on?

Chrome (including Arc, Brave, Opera, Vivaldi)

### Describe the bug

When I click the Report button for a project, it just takes me to https://modrinth.com/auth/sign-in which instantly redirects to https://modrinth.com/dashboard without any actual steps to report the project. It also says I have no active reports when I go to https://modrinth.com/dashboard/reports

I've tried logging out and back in on Modrinth, but it didn't work

Console just says this:
image

### Steps to reproduce

1. Go to a project
2. Click the red Report button
3. It'll take you to your dashboard without reporting the project

### Expected behavior

I've never actually reported a project before (when it was working), so I'm not exactly sure what *should* happen, but I definitely don't think it should just take me to the dashboard

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ToBinio**
fixes #2172

### CODE REVIEW

**Review by Erb3 — APPROVED** [review]
Tested locally with and without the changes, this PR does fix the issue.

**Review by Geometrically — APPROVED** [review]

**Comment by Geometrically** [comment]
please fix lint

**Comment by ToBinio** [comment]
> please fix lint

done

**Review by Erb3 — APPROVED** [review]

**Review by Prospector — APPROVED** [review]

**Comment by xad0x** [comment]
How can i use/apply this fix? (I don't know anything about coding etc.)

**Comment by ToBinio** [comment]
this fix should already run in production, atleased for me it also work again. 
where are you running into the issue?

**Comment by xad0x** [comment]
grafik

**Comment by xad0x** [comment]
i'm on linux if that helps and i'm using the newest beta version of modrinth

**Comment by ToBinio** [comment]
I probably should have named the Pr better...
this was a frontend fix - the app still does not have that functionality

**Comment by xad0x** [comment]
oh 😅

**Pull request merged**
